# Generated by Django 5.2.3 on 2025-06-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
