# Generated by Django 5.2.3 on 2025-06-30 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_likeandcomments_like_likeandcomments_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeandcomments',
            name='likes',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
