# Generated by Django 5.2.3 on 2025-06-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_likeandcomments_likes_posts_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeAndComments',
            new_name='Comments',
        ),
    ]
